# Generated by Django 5.2.4 on 2025-07-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
