# Generated by Django 5.2.4 on 2025-07-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsmodel_deleted_at_newsmodel_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodel',
            options={},
        ),
    ]
