# Generated by Django 5.2.4 on 2025-07-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsmodel_description_en_newsmodel_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='title_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='title_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='title_uz',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
