# Generated by Django 5.2.4 on 2025-07-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newsmodel_title_alter_newsmodel_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='slug_uz',
        ),
    ]
