# Generated by Django 5.2.4 on 2025-07-11 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_uz', models.CharField(max_length=100, null=True, unique=True)),
                ('name_en', models.CharField(max_length=100, null=True, unique=True)),
                ('name_ru', models.CharField(max_length=100, null=True, unique=True)),
                ('verbose_name', models.CharField(max_length=255, verbose_name='Display Name')),
                ('verbose_name_uz', models.CharField(max_length=255, null=True, verbose_name='Display Name')),
                ('verbose_name_en', models.CharField(max_length=255, null=True, verbose_name='Display Name')),
                ('verbose_name_ru', models.CharField(max_length=255, null=True, verbose_name='Display Name')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('name_uz', models.CharField(max_length=300, null=True)),
                ('name_en', models.CharField(max_length=300, null=True)),
                ('name_ru', models.CharField(max_length=300, null=True)),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcategory')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('key_uz', models.CharField(max_length=100, null=True)),
                ('key_en', models.CharField(max_length=100, null=True)),
                ('key_ru', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(max_length=500)),
                ('value_uz', models.CharField(max_length=500, null=True)),
                ('value_en', models.CharField(max_length=500, null=True)),
                ('value_ru', models.CharField(max_length=500, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='product.productmodel')),
            ],
        ),
    ]
