# Generated by Django 5.2.4 on 2025-07-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='verbose_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Display Name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='verbose_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Display Name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='verbose_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Display Name'),
        ),
        migrations.AddField(
            model_name='productfield',
            name='key_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productfield',
            name='key_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productfield',
            name='key_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productfield',
            name='value_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productfield',
            name='value_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productfield',
            name='value_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='name_uz',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
