# Generated by Django 5.2.4 on 2025-07-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productcategory_name_en_productcategory_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfield',
            name='value',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productfield',
            name='value_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productfield',
            name='value_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productfield',
            name='value_uz',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
