# Generated by Django 5.2.4 on 2025-07-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_product_productmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.CharField(choices=[('drone', 'Tactical Drones'), ('communication', 'Secure Communication Systems'), ('vehicle', 'Armored Vehicles'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
