# Generated by Django 5.2.4 on 2025-07-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productmodel_deleted_at_productmodel_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={},
        ),
    ]
