# Generated by Django 5.2.4 on 2025-07-16 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='verbose_name_en',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='verbose_name_ru',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='verbose_name_uz',
        ),
    ]
