# Generated by Django 5.2.4 on 2025-07-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodel',
            name='info',
            field=models.TextField(default='No info yet'),
            preserve_default=False,
        ),
    ]
