# Generated by Django 5.2.4 on 2025-07-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_partnersmodel_delete_homemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/partners/'),
        ),
    ]
