# Generated by Django 5.2.4 on 2025-07-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/about/'),
        ),
    ]
