# Generated by Django 5.2.4 on 2025-07-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutmodel_deleted_at_aboutmodel_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutmodel',
            options={},
        ),
    ]
