# Generated by Django 5.2.4 on 2025-07-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_aboutmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
